const municipios_clave =
{
    "Aguascalientes": {
        "Aguascalientes": "001",
        "San Francisco de los Romo": "011",
        "El Llano": "010",
        "Rincón de Romos": "007",
        "Cosío": "004",
        "San José de Gracia": "008",
        "Tepezalá": "009",
        "Pabellón de Arteaga": "006",
        "Asientos": "002",
        "Calvillo": "003",
        "Jesús María": "005"
    },
    "Baja California": {
        "Mexicali": "002",
        "Tecate": "003",
        "Tijuana": "004",
        "Playas de Rosarito": "005",
        "Ensenada": "001",
        "San Quintín": "006"
    },
    "Baja California Sur": {
        "La Paz": "003",
        "Los Cabos": "008",
        "Comondú": "001",
        "Loreto": "009",
        "Mulegé": "002"
    },
    "Campeche": {
        "Campeche": "002",
        "Carmen": "003",
        "Palizada": "007",
        "Candelaria": "011",
        "Escárcega": "009",
        "Champotón": "004",
        "Seybaplaya": "012",
        "Hopelchén": "006",
        "Calakmul": "010",
        "Tenabo": "008",
        "Hecelchakán": "005",
        "Calkiní": "001"
    },
    "Coahuila": {
        "Saltillo": "030",
        "Arteaga": "004",
        "Juárez": "015",
        "Progreso": "026",
        "Escobedo": "008",
        "San Buenaventura": "031",
        "Abasolo": "001",
        "Candela": "005",
        "Frontera": "010",
        "Monclova": "018",
        "Castaños": "006",
        "Ramos Arizpe": "027",
        "General Cepeda": "011",
        "Piedras Negras": "025",
        "Nava": "022",
        "Acuña": "002",
        "Múzquiz": "020",
        "Jiménez": "014",
        "Zaragoza": "038",
        "Morelos": "019",
        "Allende": "003",
        "Villa Unión": "037",
        "Guerrero": "012",
        "Hidalgo": "013",
        "Sabinas": "028",
        "San Juan de Sabinas": "032",
        "Torreón": "035",
        "Matamoros": "017",
        "Viesca": "036",
        "Ocampo": "023",
        "Nadadores": "021",
        "Sierra Mojada": "034",
        "Cuatro Ciénegas": "007",
        "Lamadrid": "016",
        "Sacramento": "029",
        "San Pedro": "033",
        "Francisco I. Madero": "009",
        "Parras": "024"
    },
    "Colima": {
        "Colima": "002",
        "Tecomán": "009",
        "Manzanillo": "007",
        "Armería": "001",
        "Coquimatlán": "004",
        "Comala": "003",
        "Cuauhtémoc": "005",
        "Ixtlahuacán": "006",
        "Minatitlán": "008",
        "Villa de Álvarez": "010"
    },
    "Chiapas": {
        "Tuxtla Gutiérrez": "101",
        "San Fernando": "079",
        "Berriozábal": "012",
        "Ocozocoautla de Espinosa": "061",
        "Suchiapa": "086",
        "Chiapa de Corzo": "027",
        "Osumacinta": "063",
        "San Cristóbal de las Casas": "078",
        "Chamula": "023",
        "Ixtapa": "044",
        "Zinacantán": "111",
        "Acala": "002",
        "Emiliano Zapata": "123",
        "Chiapilla": "028",
        "San Lucas": "110",
        "Teopisca": "094",
        "Amatenango del Valle": "007",
        "Chanal": "024",
        "Oxchuc": "064",
        "Huixtán": "038",
        "Tenejapa": "093",
        "Mitontic": "056",
        "Reforma": "074",
        "Juárez": "048",
        "Pichucalco": "068",
        "Sunuapa": "088",
        "Ostuacán": "062",
        "Francisco León": "033",
        "Ixtacomitán": "043",
        "Solosuchiapa": "084",
        "Ixtapangajoya": "045",
        "Mezcalapa": "124",
        "Tecpatán": "092",
        "Copainalá": "021",
        "Chicoasén": "029",
        "Coapilla": "018",
        "Pantepec": "067",
        "Tapalapa": "090",
        "Ocotepec": "060",
        "Chapultenango": "025",
        "Amatán": "005",
        "Huitiupán": "039",
        "Ixhuatán": "042",
        "Tapilula": "091",
        "Rayón": "073",
        "Pueblo Nuevo Solistahuacán": "072",
        "Rincón Chamula San Pedro": "121",
        "Jitotol": "047",
        "Bochil": "013",
        "Soyaló": "085",
        "San Juan Cancuc": "112",
        "Sabanilla": "076",
        "Simojovel": "081",
        "San Andrés Duraznal": "118",
        "El Bosque": "014",
        "Chalchihuitán": "022",
        "Larráinzar": "049",
        "Santiago el Pinar": "119",
        "Chenalhó": "026",
        "Aldama": "113",
        "Pantelhó": "066",
        "Sitalá": "082",
        "Salto de Agua": "077",
        "Tila": "096",
        "Tumbalá": "100",
        "Yajalón": "109",
        "Ocosingo": "059",
        "Chilón": "031",
        "Benemérito de las Américas": "114",
        "Marqués de Comillas": "116",
        "Palenque": "065",
        "La Libertad": "050",
        "Catazajá": "016",
        "Comitán de Domínguez": "019",
        "Tzimol": "104",
        "Chicomuselo": "030",
        "Bella Vista": "011",
        "Frontera Comalapa": "034",
        "La Trinitaria": "099",
        "La Independencia": "041",
        "Maravilla Tenejapa": "115",
        "Las Margaritas": "052",
        "Altamirano": "004",
        "Venustiano Carranza": "106",
        "Totolapa": "098",
        "Nicolás Ruíz": "058",
        "Las Rosas": "075",
        "La Concordia": "020",
        "Ángel Albino Corzo": "008",
        "Montecristo de Guerrero": "117",
        "Socoltenango": "083",
        "Cintalapa": "017",
        "Jiquipilas": "046",
        "Arriaga": "009",
        "Villaflores": "108",
        "Tonalá": "097",
        "Villa Corzo": "107",
        "El Parral": "122",
        "Pijijiapan": "069",
        "Mapastepec": "051",
        "Acapetahua": "003",
        "Acacoyagua": "001",
        "Escuintla": "032",
        "Villa Comaltitlán": "071",
        "Huixtla": "040",
        "Mazatán": "054",
        "Huehuetán": "037",
        "Tuzantán": "103",
        "Tapachula": "089",
        "Suchiate": "087",
        "Frontera Hidalgo": "035",
        "Metapa": "055",
        "Tuxtla Chico": "102",
        "Unión Juárez": "105",
        "Cacahoatán": "015",
        "Motozintla": "057",
        "Mazapa de Madero": "053",
        "Amatenango de la Frontera": "006",
        "Bejucal de Ocampo": "010",
        "La Grandeza": "036",
        "El Porvenir": "070",
        "Siltepec": "080",
        "Honduras de la Sierra": "125",
        "Capitán Luis Ángel Vidal": "120"
    },
    "Chihuahua": {
        "Chihuahua": "019",
        "Cuauhtémoc": "017",
        "Riva Palacio": "054",
        "Aquiles Serdán": "004",
        "Bachíniva": "006",
        "Guerrero": "031",
        "Nuevo Casas Grandes": "050",
        "Ascensión": "005",
        "Janos": "035",
        "Casas Grandes": "013",
        "Galeana": "023",
        "Buenaventura": "010",
        "Gómez Farías": "025",
        "Ignacio Zaragoza": "034",
        "Madera": "040",
        "Namiquipa": "048",
        "Temósachic": "063",
        "Matachí": "043",
        "Juárez": "037",
        "Guadalupe": "028",
        "Praxedis G. Guerrero": "053",
        "Ahumada": "001",
        "Coyame del Sotol": "015",
        "Ojinaga": "052",
        "Aldama": "002",
        "Julimes": "038",
        "Manuel Benavides": "042",
        "Delicias": "021",
        "Rosales": "055",
        "Meoqui": "045",
        "Dr. Belisario Domínguez": "022",
        "Satevó": "061",
        "San Francisco de Borja": "057",
        "Nonoava": "049",
        "Guachochi": "027",
        "Bocoyna": "009",
        "Cusihuiriachi": "018",
        "Gran Morelos": "026",
        "Santa Isabel": "024",
        "Carichí": "012",
        "Uruachi": "066",
        "Ocampo": "051",
        "Moris": "047",
        "Chínipas": "020",
        "Maguarichi": "041",
        "Guazapares": "030",
        "Batopilas de Manuel Gómez Morín": "008",
        "Urique": "065",
        "Morelos": "046",
        "Guadalupe y Calvo": "029",
        "San Francisco del Oro": "059",
        "Rosario": "056",
        "Huejotitán": "033",
        "El Tule": "064",
        "Balleza": "007",
        "Santa Bárbara": "060",
        "Camargo": "011",
        "Saucillo": "062",
        "Valle de Zaragoza": "067",
        "La Cruz": "016",
        "San Francisco de Conchos": "058",
        "Hidalgo del Parral": "032",
        "Allende": "003",
        "López": "039",
        "Matamoros": "044",
        "Jiménez": "036",
        "Coronado": "014"
    },
    "Ciudad de Mexico": {
        "Álvaro Obregón": "010",
        "Azcapotzalco": "002",
        "Benito Juárez": "014",
        "Coyoacán": "003",
        "Cuajimalpa de Morelos": "004",
        "Cuauhtémoc": "015",
        "Gustavo A. Madero": "005",
        "Iztacalco": "006",
        "Iztapalapa": "007",
        "La Magdalena Contreras": "008",
        "Miguel Hidalgo": "016",
        "Milpa Alta": "009",
        "Tláhuac": "011",
        "Tlalpan": "012",
        "Venustiano Carranza": "017",
        "Xochimilco": "013"
    },
    "Durango": {
        "Durango": "005",
        "Canatlán": "001",
        "Nuevo Ideal": "039",
        "Coneto de Comonfort": "003",
        "San Juan del Río": "028",
        "Canelas": "002",
        "Topia": "037",
        "Tamazula": "034",
        "Santiago Papasquiaro": "032",
        "Otáez": "019",
        "San Dimas": "026",
        "Guadalupe Victoria": "008",
        "Peñón Blanco": "021",
        "Pánuco de Coronado": "020",
        "Poanas": "022",
        "Nombre de Dios": "016",
        "Vicente Guerrero": "038",
        "Súchil": "033",
        "Pueblo Nuevo": "023",
        "Mezquital": "014",
        "Gómez Palacio": "007",
        "Lerdo": "012",
        "Mapimí": "013",
        "Tlahualilo": "036",
        "Hidalgo": "010",
        "Ocampo": "017",
        "Guanaceví": "009",
        "San Bernardo": "025",
        "Indé": "011",
        "San Pedro del Gallo": "030",
        "Tepehuanes": "035",
        "El Oro": "018",
        "Nazas": "015",
        "San Luis del Cordero": "029",
        "Rodeo": "024",
        "Cuencamé": "004",
        "Santa Clara": "031",
        "San Juan de Guadalupe": "027",
        "General Simón Bolívar": "006"
    },
    "Guanajuato": {
        "Guanajuato": "015",
        "Silao de la Victoria": "037",
        "Romita": "026",
        "San Francisco del Rincón": "031",
        "Purísima del Rincón": "025",
        "Manuel Doblado": "008",
        "Irapuato": "017",
        "Salamanca": "027",
        "Pueblo Nuevo": "024",
        "Pénjamo": "023",
        "Cuerámaro": "012",
        "Abasolo": "001",
        "Huanímaro": "016",
        "León": "020",
        "San Felipe": "030",
        "Ocampo": "022",
        "San Miguel de Allende": "003",
        "Dolores Hidalgo Cuna de la Independencia Nacional": "014",
        "San Diego de la Unión": "029",
        "San Luis de la Paz": "033",
        "Victoria": "043",
        "Xichú": "045",
        "Atarjea": "006",
        "Santa Catarina": "034",
        "Doctor Mora": "013",
        "Tierra Blanca": "040",
        "San José Iturbide": "032",
        "Celaya": "007",
        "Apaseo el Grande": "005",
        "Comonfort": "009",
        "Santa Cruz de Juventino Rosas": "035",
        "Villagrán": "044",
        "Cortazar": "011",
        "Valle de Santiago": "042",
        "Jaral del Progreso": "018",
        "Apaseo el Alto": "004",
        "Jerécuaro": "019",
        "Coroneo": "010",
        "Acámbaro": "002",
        "Tarimoro": "039",
        "Tarandacuao": "038",
        "Moroleón": "021",
        "Salvatierra": "028",
        "Yuriria": "046",
        "Santiago Maravatío": "036",
        "Uriangato": "041"
    },
    "Guerrero": {
        "Chilpancingo de los Bravo": "029",
        "General Heliodoro Castillo": "032",
        "Leonardo Bravo": "040",
        "Tixtla de Guerrero": "061",
        "Ayutla de los Libres": "012",
        "Mochitlán": "044",
        "Quechultenango": "051",
        "Tecoanapa": "056",
        "Acapulco de Juárez": "001",
        "Juan R. Escudero": "039",
        "San Marcos": "053",
        "Iguala de la Independencia": "035",
        "Huitzuco de los Figueroa": "034",
        "Tepecoacuilco de Trujano": "059",
        "Eduardo Neri": "075",
        "Taxco de Alarcón": "055",
        "Buenavista de Cuéllar": "015",
        "Tetipac": "060",
        "Pilcaya": "049",
        "Teloloapan": "058",
        "Ixcateopan de Cuauhtémoc": "037",
        "Pedro Ascencio Alquisiras": "047",
        "General Canuto A. Neri": "031",
        "Arcelia": "007",
        "Apaxtla": "006",
        "Cuetzala del Progreso": "026",
        "Cocula": "017",
        "Tlapehuala": "067",
        "Cutzamala de Pinzón": "027",
        "Pungarabato": "050",
        "Tlalchapa": "064",
        "Coyuca de Catalán": "022",
        "Ajuchitlán del Progreso": "003",
        "Zirándaro": "073",
        "San Miguel Totolapan": "054",
        "La Unión de Isidoro Montes de Oca": "068",
        "Petatlán": "048",
        "Coahuayutla de José María Izazaga": "016",
        "Zihuatanejo de Azueta": "038",
        "Técpan de Galeana": "057",
        "Atoyac de Álvarez": "011",
        "Benito Juárez": "014",
        "Coyuca de Benítez": "021",
        "Olinalá": "045",
        "Atenango del Río": "008",
        "Copalillo": "019",
        "Cualác": "024",
        "Chilapa de Álvarez": "028",
        "José Joaquín de Herrera": "079",
        "Ahuacuotzingo": "002",
        "Zitlala": "074",
        "Mártir de Cuilapan": "042",
        "Huamuxtitlán": "033",
        "Xochihuehuetlán": "070",
        "Alpoyeca": "005",
        "Tlapa de Comonfort": "066",
        "Tlalixtaquilla de Maldonado": "065",
        "Xalpatláhuac": "069",
        "Zapotitlán Tablas": "072",
        "Acatepec": "076",
        "Atlixtac": "010",
        "Copanatoyac": "020",
        "Malinaltepec": "041",
        "Iliatenco": "081",
        "Tlacoapa": "063",
        "Atlamajalcingo del Monte": "009",
        "San Luis Acatlán": "052",
        "Metlatónoc": "043",
        "Cochoapa el Grande": "078",
        "Alcozauca de Guerrero": "004",
        "Ometepec": "046",
        "Tlacoachistlahuaca": "062",
        "Xochistlahuaca": "071",
        "Florencio Villarreal": "030",
        "Cuautepec": "025",
        "Copala": "018",
        "Azoyú": "013",
        "Juchitán": "080",
        "Marquelia": "077",
        "Cuajinicuilapa": "023",
        "Igualapa": "036"
    },
    "Hidalgo": {
        "Pachuca de Soto": "048",
        "Mineral del Chico": "038",
        "Mineral del Monte": "039",
        "Ajacuba": "005",
        "San Agustín Tlaxiaca": "052",
        "Mineral de la Reforma": "051",
        "Zapotlán de Juárez": "082",
        "Jacala de Ledezma": "031",
        "Pisaflores": "049",
        "Pacula": "047",
        "La Misión": "040",
        "Chapulhuacán": "018",
        "Ixmiquilpan": "030",
        "Zimapán": "084",
        "Nicolás Flores": "043",
        "Cardonal": "015",
        "Tasquillo": "058",
        "Alfajayucan": "006",
        "Huichapan": "029",
        "Tecozautla": "059",
        "Nopala de Villagrán": "044",
        "Actopan": "003",
        "Santiago de Anaya": "055",
        "San Salvador": "054",
        "Francisco I. Madero": "023",
        "El Arenal": "009",
        "Mixquiahuala de Juárez": "041",
        "Progreso de Obregón": "050",
        "Chilcuautla": "019",
        "Tezontepec de Aldama": "067",
        "Tlahuelilpan": "070",
        "Tula de Allende": "076",
        "Tepeji del Río de Ocampo": "063",
        "Chapantongo": "017",
        "Tepetitlán": "064",
        "Tetepango": "065",
        "Tlaxcoapan": "074",
        "Atitalaquia": "010",
        "Atotonilco de Tula": "013",
        "Huejutla de Reyes": "028",
        "San Felipe Orizatlán": "046",
        "Jaltocán": "032",
        "Huautla": "025",
        "Atlapexco": "011",
        "Huazalingo": "026",
        "Yahualica": "080",
        "Xochiatipan": "078",
        "Molango de Escamilla": "042",
        "Tepehuacán de Guerrero": "062",
        "Lolotla": "034",
        "Tlanchinol": "073",
        "Tlahuiltepa": "071",
        "Juárez Hidalgo": "033",
        "Zacualtipán de Ángeles": "081",
        "Calnali": "014",
        "Xochicoatlán": "079",
        "Tianguistengo": "068",
        "Atotonilco el Grande": "012",
        "Eloxochitlán": "020",
        "Metztitlán": "037",
        "San Agustín Metzquititlán": "036",
        "Metepec": "035",
        "Huehuetla": "027",
        "San Bartolo Tutotepec": "053",
        "Agua Blanca de Iturbide": "004",
        "Tenango de Doria": "060",
        "Huasca de Ocampo": "024",
        "Acatlán": "001",
        "Omitlán de Juárez": "045",
        "Epazoyucan": "022",
        "Tulancingo de Bravo": "077",
        "Acaxochitlán": "002",
        "Cuautepec de Hinojosa": "016",
        "Santiago Tulantepec de Lugo Guerrero": "056",
        "Singuilucan": "057",
        "Tizayuca": "069",
        "Zempoala": "083",
        "Tolcayuca": "075",
        "Villa de Tezontepec": "066",
        "Apan": "008",
        "Tlanalapa": "072",
        "Almoloya": "007",
        "Emiliano Zapata": "021",
        "Tepeapulco": "061"
    },
    "Jalisco": {
        "Guadalajara": "039",
        "Zapopan": "120",
        "San Cristóbal de la Barranca": "071",
        "Ixtlahuacán del Río": "045",
        "Tala": "083",
        "El Arenal": "009",
        "Amatitán": "005",
        "Tonalá": "101",
        "Zapotlanejo": "124",
        "Acatic": "001",
        "Cuquío": "029",
        "San Pedro Tlaquepaque": "098",
        "Tlajomulco de Zúñiga": "097",
        "El Salto": "070",
        "Acatlán de Juárez": "002",
        "Villa Corona": "114",
        "Zacoalco de Torres": "119",
        "Atemajac de Brizuela": "010",
        "Jocotepec": "050",
        "Ixtlahuacán de los Membrillos": "044",
        "Juanacatlán": "051",
        "Chapala": "030",
        "Poncitlán": "066",
        "Zapotlán del Rey": "123",
        "Huejuquilla el Alto": "042",
        "Mezquitic": "061",
        "Villa Guerrero": "115",
        "Bolaños": "019",
        "Totatiche": "104",
        "Colotlán": "025",
        "Santa María de los Ángeles": "081",
        "Huejúcar": "041",
        "Chimaltitán": "031",
        "San Martín de Bolaños": "076",
        "Tequila": "094",
        "Hostotipaquillo": "040",
        "Magdalena": "055",
        "Etzatlán": "036",
        "San Marcos": "075",
        "San Juanito de Escobedo": "007",
        "Ameca": "006",
        "Ahualulco de Mercado": "003",
        "Teuchitlán": "095",
        "San Martín Hidalgo": "077",
        "Guachinango": "038",
        "Mixtlán": "062",
        "Mascota": "058",
        "San Sebastián del Oeste": "080",
        "San Juan de los Lagos": "073",
        "Jalostotitlán": "046",
        "San Miguel el Alto": "078",
        "San Julián": "074",
        "Arandas": "008",
        "San Ignacio Cerro Gordo": "125",
        "Teocaltiche": "091",
        "Villa Hidalgo": "116",
        "Encarnación de Díaz": "035",
        "Yahualica de González Gallo": "118",
        "Mexticacán": "060",
        "Cañadas de Obregón": "117",
        "Valle de Guadalupe": "111",
        "Lagos de Moreno": "053",
        "Ojuelos de Jalisco": "064",
        "Unión de San Antonio": "109",
        "San Diego de Alejandría": "072",
        "Tepatitlán de Morelos": "093",
        "Tototlán": "105",
        "Atotonilco el Alto": "013",
        "Ocotlán": "063",
        "Jamay": "047",
        "La Barca": "018",
        "Ayotlán": "016",
        "Jesús María": "048",
        "Degollado": "033",
        "Unión de Tula": "110",
        "Ayutla": "017",
        "Atenguillo": "012",
        "Cuautla": "028",
        "Atengo": "011",
        "Talpa de Allende": "084",
        "Puerto Vallarta": "067",
        "Cabo Corrientes": "020",
        "Tomatlán": "100",
        "Cocula": "024",
        "Tecolotlán": "088",
        "Tenamaxtlán": "090",
        "Juchitlán": "052",
        "Chiquilistlán": "032",
        "Ejutla": "034",
        "El Limón": "054",
        "El Grullo": "037",
        "Tonaya": "102",
        "Tuxcacuesco": "106",
        "Villa Purificación": "068",
        "La Huerta": "043",
        "Autlán de Navarro": "015",
        "Casimiro Castillo": "021",
        "Cuautitlán de García Barragán": "027",
        "Cihuatlán": "022",
        "Zapotlán el Grande": "023",
        "Gómez Farías": "079",
        "Concepción de Buenos Aires": "026",
        "Atoyac": "014",
        "Techaluta de Montenegro": "089",
        "Teocuitatlán de Corona": "092",
        "Sayula": "082",
        "Tapalpa": "086",
        "Amacueca": "004",
        "Tizapán el Alto": "096",
        "Tuxcueca": "107",
        "La Manzanilla de la Paz": "057",
        "Mazamitla": "059",
        "Valle de Juárez": "112",
        "Quitupan": "069",
        "Zapotiltic": "121",
        "Tamazula de Gordiano": "085",
        "San Gabriel": "113",
        "Tolimán": "099",
        "Zapotitlán de Vadillo": "122",
        "Tuxpan": "108",
        "Tonila": "103",
        "Pihuamo": "065",
        "Tecalitlán": "087",
        "Jilotlán de los Dolores": "049",
        "Santa María del Oro": "056"
    },
    "Estado de Mexico": {
        "Toluca": "106",
        "Acambay de Ruíz Castañeda": "001",
        "Aculco": "003",
        "Temascalcingo": "085",
        "Atlacomulco": "014",
        "Timilpan": "102",
        "Morelos": "056",
        "El Oro": "064",
        "San Felipe del Progreso": "074",
        "San José del Rincón": "124",
        "Jocotitlán": "048",
        "Ixtlahuaca": "042",
        "Jiquipilco": "047",
        "Temoaya": "087",
        "Almoloya de Juárez": "005",
        "Villa Victoria": "114",
        "Villa de Allende": "111",
        "Donato Guerra": "032",
        "Ixtapan del Oro": "041",
        "Santo Tomás": "078",
        "Otzoloapan": "066",
        "Zacazonapan": "116",
        "Valle de Bravo": "110",
        "Amanalco": "007",
        "Temascaltepec": "086",
        "Zinacantepec": "118",
        "Tejupilco": "082",
        "Luvianos": "123",
        "San Simón de Guerrero": "077",
        "Amatepec": "008",
        "Tlatlaya": "105",
        "Sultepec": "080",
        "Texcaltitlán": "097",
        "Coatepec Harinas": "021",
        "Villa Guerrero": "113",
        "Zacualpan": "117",
        "Almoloya de Alquisiras": "004",
        "Ixtapan de la Sal": "040",
        "Tonatico": "107",
        "Zumpahuacán": "119",
        "Lerma": "051",
        "Xonacatlán": "115",
        "Otzolotepec": "067",
        "San Mateo Atenco": "076",
        "Metepec": "054",
        "Mexicaltzingo": "055",
        "Calimaya": "018",
        "Chapultepec": "027",
        "San Antonio la Isla": "073",
        "Tenango del Valle": "090",
        "Rayón": "072",
        "Joquicingo": "049",
        "Tenancingo": "088",
        "Malinalco": "052",
        "Ocuilan": "063",
        "Atizapán": "012",
        "Almoloya del Río": "006",
        "Texcalyacac": "098",
        "Tianguistenco": "101",
        "Xalatlaco": "043",
        "Capulhuac": "019",
        "Ocoyoacac": "062",
        "Huixquilucan": "037",
        "Atizapán de Zaragoza": "013",
        "Naucalpan de Juárez": "057",
        "Tlalnepantla de Baz": "104",
        "Polotitlán": "071",
        "Jilotepec": "045",
        "Soyaniquilpan de Juárez": "079",
        "Villa del Carbón": "112",
        "Chapa de Mota": "026",
        "Nicolás Romero": "060",
        "Isidro Fabela": "038",
        "Jilotzingo": "046",
        "Tepotzotlán": "095",
        "Coyotepec": "023",
        "Huehuetoca": "035",
        "Cuautitlán Izcalli": "121",
        "Teoloyucan": "091",
        "Cuautitlán": "024",
        "Melchor Ocampo": "053",
        "Tultitlán": "109",
        "Tultepec": "108",
        "Ecatepec de Morelos": "033",
        "Zumpango": "120",
        "Tequixquiac": "096",
        "Apaxco": "010",
        "Hueypoxtla": "036",
        "Coacalco de Berriozábal": "020",
        "Tecámac": "081",
        "Jaltenco": "044",
        "Tonanitla": "125",
        "Nextlalpan": "059",
        "Teotihuacán": "092",
        "San Martín de las Pirámides": "075",
        "Acolman": "002",
        "Otumba": "065",
        "Axapusco": "016",
        "Nopaltepec": "061",
        "Temascalapa": "084",
        "Tezoyuca": "100",
        "Chiautla": "028",
        "Papalotla": "069",
        "Tepetlaoxtoc": "093",
        "Texcoco": "099",
        "Chiconcuac": "030",
        "Atenco": "011",
        "Chimalhuacán": "031",
        "Chicoloapan": "029",
        "La Paz": "070",
        "Ixtapaluca": "039",
        "Chalco": "025",
        "Valle de Chalco Solidaridad": "122",
        "Temamatla": "083",
        "Cocotitlán": "022",
        "Tlalmanalco": "103",
        "Ayapango": "017",
        "Tenango del Aire": "089",
        "Ozumba": "068",
        "Juchitepec": "050",
        "Tepetlixpa": "094",
        "Amecameca": "009",
        "Atlautla": "015",
        "Ecatzingo": "034",
        "Nezahualcóyotl": "058"
    },
    "Michoacan": {
        "Morelia": "053",
        "Huaniqueo": "037",
        "Coeneo": "016",
        "Quiroga": "073",
        "Tzintzuntzan": "100",
        "Lagunillas": "048",
        "Acuitzio": "001",
        "Madero": "049",
        "Puruándiro": "071",
        "José Sixto Verduzco": "113",
        "Angamacutiro": "004",
        "Panindícuaro": "063",
        "Zacapu": "107",
        "Tlazazalca": "094",
        "Purépero": "070",
        "Jiménez": "044",
        "Morelos": "054",
        "Huandacareo": "036",
        "Cuitzeo": "020",
        "Chucándiro": "027",
        "Copándaro": "018",
        "Tarímbaro": "088",
        "Santa Ana Maya": "078",
        "Álvaro Obregón": "003",
        "Zinapécuaro": "110",
        "Indaparapeo": "040",
        "Queréndaro": "072",
        "Sahuayo": "076",
        "Briseñas": "011",
        "Cojumatlán de Régules": "074",
        "Venustiano Carranza": "103",
        "Pajacuarán": "062",
        "Vista Hermosa": "105",
        "Tanhuato": "086",
        "Yurécuaro": "106",
        "Ixtlán": "042",
        "La Piedad": "069",
        "Numarán": "060",
        "Churintzio": "028",
        "Zináparo": "109",
        "Penjamillo": "067",
        "Marcos Castellanos": "051",
        "Jiquilpan": "045",
        "Villamar": "104",
        "Chavinda": "023",
        "Zamora": "108",
        "Ecuandureo": "030",
        "Tangancícuaro": "085",
        "Chilchota": "025",
        "Jacona": "043",
        "Tangamandapio": "084",
        "Cotija": "019",
        "Tocumbo": "095",
        "Tingüindín": "091",
        "Uruapan": "102",
        "Charapan": "021",
        "Paracho": "065",
        "Cherán": "024",
        "Nahuatzen": "056",
        "Tingambato": "090",
        "Los Reyes": "075",
        "Peribán": "068",
        "Tancítaro": "083",
        "Nuevo Parangaricutiro": "058",
        "Buenavista": "012",
        "Tepalcatepec": "089",
        "Aguililla": "002",
        "Apatzingán": "006",
        "Parácuaro": "064",
        "Coahuayana": "014",
        "Chinicuila": "026",
        "Coalcomán de Vázquez Pallares": "015",
        "Aquila": "008",
        "Tumbiscatío": "096",
        "Arteaga": "010",
        "Lázaro Cárdenas": "052",
        "Epitacio Huerta": "031",
        "Contepec": "017",
        "Tlalpujahua": "093",
        "Hidalgo": "034",
        "Maravatío": "050",
        "Irimbo": "041",
        "Senguio": "080",
        "Charo": "022",
        "Tzitzio": "101",
        "Tiquicheo de Nicolás Romero": "092",
        "Aporo": "007",
        "Angangueo": "005",
        "Tuxpan": "098",
        "Ocampo": "061",
        "Jungapeo": "047",
        "Zitácuaro": "112",
        "Tuzantla": "099",
        "Juárez": "046",
        "Susupuato": "081",
        "Pátzcuaro": "066",
        "Erongarícuaro": "032",
        "Huiramba": "039",
        "Tacámbaro": "082",
        "Turicato": "097",
        "Ziracuaretiro": "111",
        "Taretan": "087",
        "Gabriel Zamora": "033",
        "Nuevo Urecho": "059",
        "Múgica": "055",
        "Salvador Escalante": "079",
        "Ario": "009",
        "La Huacana": "035",
        "Churumuco": "029",
        "Nocupétaro": "057",
        "Carácuaro": "013",
        "Huetamo": "038",
        "San Lucas": "077"
    },
    "Morelos": {
        "Cuernavaca": "007",
        "Huitzilac": "009",
        "Tepoztlán": "020",
        "Tlalnepantla": "023",
        "Tlayacapan": "026",
        "Jiutepec": "011",
        "Temixco": "018",
        "Miacatlán": "015",
        "Coatetelco": "034",
        "Coatlán del Río": "005",
        "Tetecala": "021",
        "Mazatepec": "014",
        "Amacuzac": "001",
        "Puente de Ixtla": "017",
        "Xoxocotla": "035",
        "Ayala": "004",
        "Yautepec": "029",
        "Cuautla": "006",
        "Emiliano Zapata": "008",
        "Tlaltizapán de Zapata": "024",
        "Zacatepec": "031",
        "Xochitepec": "028",
        "Tetela del Volcán": "022",
        "Hueyapan": "036",
        "Yecapixtla": "030",
        "Totolapan": "027",
        "Atlatlahucan": "002",
        "Ocuituco": "016",
        "Temoac": "033",
        "Zacualpan de Amilpas": "032",
        "Jojutla": "012",
        "Tepalcingo": "019",
        "Jonacatepec de Leandro Valle": "013",
        "Axochiapan": "003",
        "Jantetelco": "010",
        "Tlaquiltenango": "025"
    },
    "Nayarit": {
        "Tepic": "017",
        "Tuxpan": "018",
        "Santiago Ixcuintla": "015",
        "Acaponeta": "001",
        "Tecuala": "016",
        "Huajicori": "005",
        "Del Nayar": "009",
        "La Yesca": "019",
        "Ruíz": "011",
        "Rosamorada": "010",
        "Compostela": "004",
        "Bahía de Banderas": "020",
        "San Blas": "012",
        "Xalisco": "008",
        "San Pedro Lagunillas": "013",
        "Santa María del Oro": "014",
        "Jala": "007",
        "Ahuacatlán": "002",
        "Ixtlán del Río": "006",
        "Amatlán de Cañas": "003"
    },
    "Nuevo Leon": {
        "Monterrey": "039",
        "Anáhuac": "005",
        "Lampazos de Naranjo": "032",
        "Mina": "037",
        "Bustamante": "008",
        "Sabinas Hidalgo": "044",
        "Villaldama": "051",
        "Vallecillo": "050",
        "Parás": "040",
        "Salinas Victoria": "045",
        "Ciénega de Flores": "012",
        "Hidalgo": "047",
        "Abasolo": "001",
        "Higueras": "028",
        "General Zuazua": "025",
        "Agualeguas": "002",
        "General Treviño": "023",
        "Cerralvo": "011",
        "Melchor Ocampo": "035",
        "García": "018",
        "General Escobedo": "021",
        "Santa Catarina": "048",
        "San Pedro Garza García": "019",
        "San Nicolás de los Garza": "046",
        "El Carmen": "010",
        "Apodaca": "006",
        "Pesquería": "041",
        "Marín": "034",
        "Doctor González": "016",
        "Los Ramones": "042",
        "Los Herreras": "027",
        "Los Aldamas": "003",
        "Doctor Coss": "015",
        "General Bravo": "020",
        "China": "013",
        "Guadalupe": "026",
        "Juárez": "031",
        "Santiago": "049",
        "Allende": "004",
        "General Terán": "022",
        "Cadereyta Jiménez": "009",
        "Montemorelos": "038",
        "Rayones": "043",
        "Linares": "033",
        "Iturbide": "030",
        "Galeana": "017",
        "Hualahuises": "029",
        "Doctor Arroyo": "014",
        "Aramberri": "007",
        "General Zaragoza": "024",
        "Mier y Noriega": "036"
    },
    "Oaxaca": {
        "Oaxaca de Juárez": "067",
        "Villa de Etla": "338",
        "San Juan Bautista Atatlahuca": "175",
        "San Jerónimo Sosola": "161",
        "San Juan Bautista Jayacatlán": "179",
        "San Francisco Telixtlahuaca": "150",
        "Santiago Tenango": "487",
        "San Pablo Huitzo": "294",
        "San Juan del Estado": "193",
        "Magdalena Apasco": "045",
        "Santiago Suchilquitongo": "483",
        "San Juan Bautista Guelache": "178",
        "Reyes Etla": "077",
        "Nazareno Etla": "063",
        "San Andrés Zautla": "102",
        "San Agustín Etla": "084",
        "Soledad Etla": "539",
        "Santo Tomás Mazaltepec": "531",
        "Guadalupe Etla": "033",
        "San Pablo Etla": "293",
        "San Felipe Tejalápam": "135",
        "San Lorenzo Cacaotepec": "227",
        "Santa María Peñoles": "426",
        "Santiago Tlazoyaltepec": "494",
        "Tlalixtac de Cabrera": "553",
        "San Jacinto Amilpas": "157",
        "San Andrés Huayápam": "091",
        "San Agustín Yatareni": "087",
        "Santo Domingo Tomaltepec": "519",
        "Santa María del Tule": "409",
        "San Juan Bautista Tuxtepec": "184",
        "Loma Bonita": "044",
        "San José Independencia": "169",
        "Cosolapa": "021",
        "Acatlán de Pérez Figueroa": "002",
        "San Miguel Soyaltepec": "278",
        "Ayotzintepec": "009",
        "San Pedro Ixcatlán": "309",
        "San José Chiltepec": "166",
        "San Felipe Jalapa de Díaz": "134",
        "Santa María Jacatepec": "417",
        "San Lucas Ojitlán": "232",
        "San Juan Bautista Valle Nacional": "559",
        "San Felipe Usila": "136",
        "Huautla de Jiménez": "041",
        "Santa María Chilchotla": "406",
        "Santa Ana Ateixtlahuaca": "354",
        "San Lorenzo Cuaunecuiltitla": "228",
        "San Francisco Huehuetlán": "142",
        "San Pedro Ocopetatillo": "322",
        "Santa Cruz Acatepec": "374",
        "Eloxochitlán de Flores Magón": "029",
        "Santiago Texcalcingo": "490",
        "Teotitlán de Flores Magón": "545",
        "Santa María Teopoxco": "434",
        "San Martín Toxpalan": "244",
        "San Jerónimo Tecóatl": "163",
        "Santa María la Asunción": "396",
        "Huautepec": "040",
        "San Juan Coatzóspam": "187",
        "San Lucas Zoquiápam": "234",
        "San Antonio Nanahuatípam": "109",
        "San José Tenango": "171",
        "San Mateo Yoloxochitlán": "249",
        "San Bartolomé Ayautla": "116",
        "Mazatlán Villa de Flores": "058",
        "San Juan de los Cués": "206",
        "Santa María Tecomavaca": "431",
        "Santa María Ixcatlán": "416",
        "San Juan Bautista Cuicatlán": "177",
        "Cuyamecalco Villa de Zaragoza": "024",
        "Santa Ana Cuauhtémoc": "355",
        "Chiquihuitlán de Benito Juárez": "027",
        "San Pedro Teutila": "330",
        "San Miguel Santa Flor": "276",
        "Santa María Tlalixtac": "438",
        "San Andrés Teotilálpam": "098",
        "San Francisco Chapulapa": "139",
        "Concepción Pápalo": "019",
        "Santos Reyes Pápalo": "527",
        "San Juan Bautista Tlacoatzintepec": "182",
        "Santa María Pápalo": "425",
        "San Juan Tepeuxila": "220",
        "San Pedro Sochiápam": "326",
        "Valerio Trujano": "558",
        "San Pedro Jocotipac": "313",
        "Santa María Texcatitlán": "436",
        "San Pedro Jaltepetongo": "311",
        "Santiago Nacaltepec": "478",
        "Natividad": "062",
        "San Juan Quiotepec": "214",
        "San Pedro Yólox": "336",
        "Santiago Comaltepec": "458",
        "Abejones": "001",
        "San Pablo Macuiltianguis": "296",
        "Ixtlán de Juárez": "042",
        "San Juan Atepec": "173",
        "San Pedro Yaneri": "335",
        "San Miguel Aloápam": "260",
        "Teococuilco de Marcos Pérez": "544",
        "Santa Ana Yareni": "359",
        "San Juan Evangelista Analco": "196",
        "Santa María Jaltianguis": "419",
        "San Miguel del Río": "267",
        "San Juan Chicomezúchil": "191",
        "Capulálpam de Méndez": "247",
        "Nuevo Zoquiápam": "504",
        "Santiago Xiacuí": "496",
        "Guelatao de Juárez": "035",
        "Santa Catarina Ixtepeji": "363",
        "San Miguel Yotao": "288",
        "Santa Catarina Lachatao": "365",
        "San Miguel Amatlán": "262",
        "Santa María Yavesía": "443",
        "Santiago Laxopa": "473",
        "San Ildefonso Villa Alta": "156",
        "Santiago Camotlán": "457",
        "San Juan Yaeé": "222",
        "Santiago Lalopa": "471",
        "San Juan Yatzona": "223",
        "Villa Talea de Castro": "280",
        "Tanetze de Zaragoza": "541",
        "San Juan Juquila Vijanos": "201",
        "San Cristóbal Lachirioag": "128",
        "Santa María Temaxcalapa": "432",
        "Santo Domingo Roayaga": "514",
        "Santa María Yalina": "442",
        "San Andrés Solaga": "097",
        "San Juan Tabaá": "216",
        "San Melchor Betaza": "257",
        "San Andrés Yaá": "100",
        "San Bartolomé Zoogocho": "120",
        "San Baltazar Yatzachi el Bajo": "114",
        "Santiago Zoochila": "503",
        "Villa Hidalgo": "038",
        "San Francisco Cajonos": "138",
        "San Mateo Cajonos": "246",
        "San Pedro Cajonos": "303",
        "Santo Domingo Xagacía": "522",
        "San Pablo Yaganiza": "299",
        "Santiago Choápam": "460",
        "Santiago Jocotepec": "468",
        "San Juan Lalana": "205",
        "Santiago Yaveo": "498",
        "San Juan Petlapa": "212",
        "San Juan Comaltepec": "189",
        "Heroica Ciudad de Huajuapan de León": "039",
        "Santiago Chazumba": "459",
        "Cosoltepec": "022",
        "San Pedro y San Pablo Tequixtepec": "340",
        "San Juan Bautista Suchitepec": "181",
        "Santa Catarina Zapoquila": "373",
        "Santiago Miltepec": "476",
        "San Jerónimo Silacayoapilla": "160",
        "Zapotitlán Palmas": "568",
        "San Andrés Dinicuiti": "089",
        "Santiago Cacaloxtepec": "456",
        "Asunción Cuyotepeji": "004",
        "Santa María Camotlán": "400",
        "Santiago Huajolotitlán": "462",
        "Santiago Tamazola": "484",
        "San Juan Cieneguilla": "186",
        "Zapotitlán Lagunas": "567",
        "San Juan Ihualtepec": "199",
        "San Nicolás Hidalgo": "290",
        "Guadalupe de Ramírez": "034",
        "San Andrés Tepetlapa": "099",
        "San Miguel Ahuehuetitlán": "259",
        "San Mateo Nejápam": "251",
        "San Juan Bautista Tlachichilco": "183",
        "Tezoatlán de Segura y Luna": "549",
        "Fresnillo de Trujano": "032",
        "Santiago Ayuquililla": "455",
        "San José Ayuquila": "165",
        "San Martín Zacatepec": "245",
        "San Miguel Amatitlán": "261",
        "Mariscala de Juárez": "055",
        "Santa Cruz Tacache de Mina": "381",
        "San Simón Zahuatlán": "352",
        "San Marcos Arteaga": "237",
        "San Jorge Nuchita": "164",
        "Santos Reyes Yucuná": "529",
        "Santo Domingo Tonalá": "520",
        "Santo Domingo Yodohino": "524",
        "San Juan Bautista Coixtlahuaca": "176",
        "Tepelmeme Villa de Morelos": "548",
        "Concepción Buenavista": "018",
        "Santiago Ihuitlán Plumas": "464",
        "Tlacotepec Plumas": "552",
        "San Francisco Teopan": "151",
        "Santa Magdalena Jicotlán": "047",
        "San Mateo Tlapiltepec": "256",
        "San Miguel Tequixtepec": "283",
        "San Miguel Tulancingo": "287",
        "Santiago Tepetlapa": "488",
        "San Cristóbal Suchixtlahuaca": "129",
        "Santa María Nativitas": "422",
        "Silacayoápam": "537",
        "Santiago Yucuyachi": "501",
        "San Lorenzo Victoria": "230",
        "San Agustín Atenango": "081",
        "Calihualá": "011",
        "Santa Cruz de Bravo": "376",
        "Ixpantepec Nieves": "065",
        "San Francisco Tlapancingo": "152",
        "Santiago del Río": "461",
        "San Pedro y San Pablo Teposcolula": "339",
        "La Trinidad Vista Hermosa": "556",
        "Villa de Tamazulápam del Progreso": "540",
        "San Pedro Nopala": "321",
        "Teotongo": "547",
        "San Antonio Acutla": "106",
        "Villa Tejúpam de la Unión": "486",
        "Santo Domingo Tonaltepec": "521",
        "Villa de Chilapa de Díaz": "405",
        "San Antonino Monte Verde": "105",
        "San Andrés Lagunas": "093",
        "San Pedro Yucunama": "341",
        "San Juan Teposcolula": "221",
        "San Bartolo Soyaltepec": "121",
        "Santiago Yolomécatl": "499",
        "San Sebastián Nicananduta": "346",
        "Santo Domingo Tlatayápam": "518",
        "Santa María Nduayaco": "423",
        "San Vicente Nuñú": "536",
        "San Pedro Topiltepec": "332",
        "Santiago Nejapilla": "479",
        "Asunción Nochixtlán": "006",
        "San Miguel Huautla": "270",
        "San Miguel Chicahua": "264",
        "Santa María Apazco": "395",
        "Santiago Apoala": "451",
        "Santa María Chachoápam": "404",
        "San Pedro Coxcaltepec Cántaros": "304",
        "Santiago Huauclilla": "463",
        "Santo Domingo Yanhuitlán": "523",
        "San Andrés Sinaxtla": "096",
        "San Juan Yucuita": "224",
        "San Juan Sayultepec": "215",
        "Santiago Tillo": "493",
        "San Francisco Chindúa": "140",
        "San Mateo Etlatongo": "250",
        "Santa Inés de Zaragoza": "569",
        "Santiago Juxtlahuaca": "469",
        "San Miguel Tlacotepec": "286",
        "San Sebastián Tecomaxtlahuaca": "348",
        "Santos Reyes Tepejillo": "528",
        "San Juan Mixtepec -Dto. 08 -": "208",
        "San Martín Peras": "242",
        "Coicoyán de las Flores": "016",
        "Heroica Ciudad de Tlaxiaco": "397",
        "San Juan Ñumí": "210",
        "San Pedro Mártir Yucuxaco": "317",
        "San Martín Huamelúlpam": "239",
        "Santa Cruz Tayata": "383",
        "Santiago Nundiche": "480",
        "Santa María del Rosario": "408",
        "San Juan Achiutla": "172",
        "Santa Catarina Tayata": "370",
        "San Cristóbal Amoltepec": "127",
        "San Miguel Achiutla": "258",
        "San Martín Itunyoso": "240",
        "Magdalena Peñasco": "050",
        "San Bartolomé Yucuañe": "119",
        "Santa Cruz Nundaco": "379",
        "San Agustín Tlacotepec": "086",
        "Santo Tomás Ocotepec": "532",
        "San Antonio Sinicahua": "110",
        "San Mateo Peñasco": "252",
        "Santa María Tataltepec": "430",
        "San Pedro Molinos": "320",
        "Santa María Yosoyúa": "445",
        "San Juan Teita": "218",
        "Magdalena Jaltepec": "046",
        "Magdalena Yodocono de Porfirio Díaz": "562",
        "San Miguel Tecomatlán": "281",
        "Magdalena Zahuatlán": "054",
        "San Francisco Nuxaño": "147",
        "San Pedro Tidaá": "331",
        "San Francisco Jaltepetongo": "144",
        "Santiago Tilantongo": "492",
        "San Juan Diuxi": "195",
        "San Andrés Nuxiño": "094",
        "San Juan Tamazola": "217",
        "Santo Domingo Nuxaá": "511",
        "Yutanduchi de Guerrero": "564",
        "San Pedro Teozacoalco": "329",
        "San Miguel Piedras": "274",
        "San Mateo Sindihui": "255",
        "Juchitán de Zaragoza": "043",
        "Ciudad Ixtepec": "014",
        "El Espinal": "030",
        "Santo Domingo Ingenio": "505",
        "Santa María Xadani": "441",
        "Santiago Niltepec": "066",
        "San Dionisio del Mar": "130",
        "Asunción Ixtaltepec": "005",
        "San Francisco del Mar": "141",
        "Unión Hidalgo": "557",
        "San Miguel Chimalapa": "265",
        "Santo Domingo Zanatepec": "525",
        "Reforma de Pineda": "075",
        "San Francisco Ixhuatán": "143",
        "San Pedro Tapanatepec": "327",
        "Chahuites": "025",
        "Santiago Zacatepec": "502",
        "Santo Domingo Tepuxtepec": "517",
        "San Juan Cotzocón": "190",
        "San Juan Mazatlán": "207",
        "Totontepec Villa de Morelos": "554",
        "Mixistlán de la Reforma": "060",
        "Santa María Tlahuitoltepec": "437",
        "Santa María Alotepec": "394",
        "Santiago Atitlán": "454",
        "Tamazulápam del Espíritu Santo": "031",
        "San Pedro y San Pablo Ayutla": "337",
        "Santa María Tepantlali": "435",
        "San Miguel Quetzaltepec": "275",
        "Asunción Cacalotepec": "003",
        "San Pedro Ocotepec": "323",
        "San Lucas Camotlán": "231",
        "Santiago Ixcuintepec": "465",
        "Matías Romero Avendaño": "057",
        "San Juan Guichicovi": "198",
        "Santo Domingo Petapa": "513",
        "Santa María Chimalapa": "407",
        "Santa María Petapa": "427",
        "El Barrio de la Soledad": "010",
        "Tlacolula de Matamoros": "551",
        "San Sebastián Abasolo": "343",
        "Villa Díaz Ordaz": "560",
        "Santa María Guelacé": "411",
        "Teotitlán del Valle": "546",
        "San Francisco Lachigoló": "145",
        "San Sebastián Teitipac": "349",
        "Santa Ana del Valle": "356",
        "San Pablo Villa de Mitla": "298",
        "Santiago Matatlán": "475",
        "Santo Domingo Albarradas": "506",
        "Rojas de Cuauhtémoc": "078",
        "San Juan Teitipac": "219",
        "Santa Cruz Papalutla": "380",
        "Magdalena Teitipac": "051",
        "San Jerónimo Tlacochahuaya": "550",
        "San Juan Guelavía": "197",
        "San Lucas Quiaviní": "233",
        "San Juan del Río": "194",
        "San Bartolomé Quialana": "118",
        "San Lorenzo Albarradas": "226",
        "San Pedro Totolápam": "333",
        "San Pedro Quiatoni": "325",
        "Santa María Zoquitlán": "449",
        "San Dionisio Ocotepec": "131",
        "San Carlos Yautepec": "125",
        "San Juan Juquila Mixes": "200",
        "Nejapa de Madero": "064",
        "Santa Ana Tavela": "357",
        "San Juan Lajarcia": "204",
        "San Bartolo Yautepec": "122",
        "Santa María Ecatepec": "410",
        "Asunción Tlacolulita": "008",
        "San Pedro Mártir Quiechapa": "316",
        "Santa María Quiegolani": "428",
        "Santa Catarina Quioquitani": "074",
        "Santa Catalina Quierí": "361",
        "Salina Cruz": "079",
        "Santiago Lachiguiri": "470",
        "Santa María Jalapa del Marqués": "418",
        "Santa María Totolapilla": "440",
        "Santiago Laollaga": "472",
        "Guevea de Humboldt": "036",
        "Santo Domingo Chihuitán": "508",
        "Santa María Guienagati": "412",
        "Magdalena Tequisistlán": "052",
        "Magdalena Tlacotepec": "053",
        "San Pedro Comitancillo": "305",
        "Santa María Mixtequilla": "421",
        "Santo Domingo Tehuantepec": "515",
        "San Pedro Huamelula": "307",
        "San Pedro Huilotepec": "308",
        "San Mateo del Mar": "248",
        "San Blas Atempa": "124",
        "Santiago Astata": "453",
        "San Miguel Tenango": "282",
        "Miahuatlán de Porfirio Díaz": "059",
        "San Nicolás": "289",
        "San Simón Almolongas": "351",
        "San Luis Amatlán": "235",
        "San José Lachiguiri": "170",
        "Sitio de Xitlapehua": "538",
        "San Francisco Logueche": "146",
        "Santa Ana": "353",
        "Santa Cruz Xitla": "384",
        "Monjas": "061",
        "San Ildefonso Amatlán": "154",
        "Santa Catarina Cuixtla": "362",
        "San José del Peñasco": "167",
        "San Cristóbal Amatlán": "126",
        "San Juan Mixtepec -Dto. 26 -": "209",
        "San Pedro Mixtepec -Dto. 26 -": "319",
        "Santa Lucía Miahuatlán": "391",
        "San Jerónimo Coatlán": "159",
        "San Sebastián Coatlán": "344",
        "San Pablo Coatlán": "291",
        "San Mateo Río Hondo": "254",
        "Santo Tomás Tamazulapan": "533",
        "San Andrés Paxtlán": "095",
        "Santa María Ozolotepec": "424",
        "San Miguel Coatlán": "263",
        "San Sebastián Río Hondo": "347",
        "San Miguel Suchixtepec": "279",
        "Santo Domingo Ozolotepec": "512",
        "San Francisco Ozolotepec": "148",
        "Santiago Xanica": "495",
        "San Marcial Ozolotepec": "236",
        "San Juan Ozolotepec": "211",
        "San Pedro Pochutla": "324",
        "Santo Domingo de Morelos": "509",
        "Santa Catarina Loxicha": "366",
        "San Agustín Loxicha": "085",
        "San Baltazar Loxicha": "113",
        "Santa María Colotepec": "401",
        "San Bartolomé Loxicha": "117",
        "Santa María Tonameca": "439",
        "Candelaria Loxicha": "012",
        "Pluma Hidalgo": "071",
        "San Pedro el Alto": "306",
        "San Mateo Piñas": "253",
        "Santa María Huatulco": "413",
        "San Miguel del Puerto": "266",
        "Putla Villa de Guerrero": "073",
        "Constancia del Rosario": "020",
        "Mesones Hidalgo": "037",
        "Santa María Zacatepec": "447",
        "San Pedro Amuzgos": "300",
        "La Reforma": "076",
        "Santa María Ipalapa": "415",
        "Chalcatongo de Hidalgo": "026",
        "Santa María Yucuhiti": "446",
        "San Esteban Atatlahuca": "133",
        "Santa Catarina Ticuá": "371",
        "Santiago Nuyoó": "481",
        "Santa Catarina Yosonotú": "372",
        "San Miguel el Grande": "269",
        "Santo Domingo Ixcatlán": "510",
        "San Pablo Tijaltepec": "297",
        "Santa Cruz Tacahua": "382",
        "Santa Lucía Monteverde": "392",
        "San Andrés Cabecera Nueva": "088",
        "Santa María Yolotepec": "444",
        "Santiago Yosondúa": "500",
        "Santa Cruz Itundujia": "377",
        "Zimatlán de Álvarez": "570",
        "San Bernardo Mixtepec": "123",
        "Santa Cruz Mixtepec": "378",
        "San Miguel Mixtepec": "271",
        "Santa María Atzompa": "399",
        "San Andrés Ixtlahuaca": "092",
        "Santa Cruz Amilpas": "375",
        "Santa Cruz Xoxocotlán": "385",
        "Santa Lucía del Camino": "390",
        "San Pedro Ixtlahuaca": "310",
        "San Antonio de la Cal": "107",
        "San Agustín de las Juntas": "083",
        "San Pablo Huixtepec": "295",
        "Ánimas Trujano": "174",
        "San Jacinto Tlacotepec": "158",
        "San Raymundo Jalpan": "342",
        "Trinidad Zaachila": "555",
        "Santa María Coyotepec": "403",
        "San Bartolo Coyotepec": "115",
        "Santa Inés Yatzeche": "389",
        "Ciénega de Zimatlán": "013",
        "San Antonio Huitepec": "108",
        "Villa de Zaachila": "565",
        "San Sebastián Tutla": "350",
        "San Miguel Peras": "273",
        "San Pablo Cuatro Venados": "292",
        "Santa Inés del Monte": "388",
        "Santa Gertrudis": "387",
        "San Antonino el Alto": "104",
        "Magdalena Mixtepec": "048",
        "Santa Catarina Quiané": "369",
        "Ayoquezco de Aldama": "398",
        "Santa Ana Tlapacoyan": "358",
        "Santa Cruz Zenzontepec": "386",
        "San Francisco Cahuacuá": "137",
        "San Mateo Yucutindoo": "566",
        "Santiago Textitlán": "491",
        "Santiago Amoltepec": "450",
        "Santa María Zaniza": "448",
        "Santo Domingo Teojomulco": "516",
        "Cuilápam de Guerrero": "023",
        "Villa Sola de Vega": "277",
        "Santa María Lachixío": "420",
        "San Vicente Lachixío": "535",
        "San Lorenzo Texmelúcan": "229",
        "Santa María Sola": "429",
        "San Francisco Sola": "149",
        "San Ildefonso Sola": "155",
        "Santiago Minas": "477",
        "Heroica Ciudad de Ejutla de Crespo": "028",
        "San Martín Tilcajete": "243",
        "Santo Tomás Jalieza": "530",
        "San Juan Chilateca": "192",
        "Ocotlán de Morelos": "068",
        "Santa Ana Zegache": "360",
        "Santiago Apóstol": "452",
        "San Antonino Castillo Velasco": "103",
        "Asunción Ocotlán": "007",
        "San Pedro Mártir": "315",
        "San Dionisio Ocotlán": "132",
        "Magdalena Ocotlán": "049",
        "San Miguel Tilquiápam": "284",
        "Santa Catarina Minas": "368",
        "San Baltazar Chichicápam": "112",
        "San Pedro Apóstol": "301",
        "Santa Lucía Ocotlán": "393",
        "San Jerónimo Taviche": "162",
        "San Andrés Zabache": "101",
        "San José del Progreso": "072",
        "Yaxe": "561",
        "San Pedro Taviche": "328",
        "San Martín de los Cansecos": "238",
        "San Martín Lachilá": "241",
        "La Pe": "069",
        "La Compañía": "017",
        "Coatecas Altas": "015",
        "San Juan Lachigalla": "203",
        "San Agustín Amatengo": "080",
        "Taniche": "542",
        "San Miguel Ejutla": "268",
        "Yogana": "563",
        "San Vicente Coatlán": "534",
        "Santiago Pinotepa Nacional": "482",
        "San Juan Cacahuatepec": "185",
        "San Juan Bautista Lo de Soto": "180",
        "Mártires de Tacubaya": "056",
        "San Sebastián Ixcapa": "345",
        "San Antonio Tepetlapa": "111",
        "Santa María Cortijo": "402",
        "Santiago Llano Grande": "474",
        "San Miguel Tlacamama": "285",
        "Santiago Tapextla": "485",
        "San José Estancia Grande": "168",
        "Santo Domingo Armenta": "507",
        "Santiago Jamiltepec": "467",
        "San Pedro Atoyac": "302",
        "San Juan Colorado": "188",
        "Santiago Ixtayutla": "466",
        "San Pedro Jicayán": "312",
        "Pinotepa de Don Luis": "070",
        "San Lorenzo": "225",
        "San Agustín Chayuco": "082",
        "San Andrés Huaxpaltepec": "090",
        "Santa Catarina Mechoacán": "367",
        "Santiago Tetepec": "489",
        "Santa María Huazolotitlán": "414",
        "Villa de Tututepec": "334",
        "Tataltepec de Valdés": "543",
        "San Juan Quiahije": "213",
        "San Miguel Panixtlahuaca": "272",
        "Santa Catarina Juquila": "364",
        "San Pedro Juchatengo": "314",
        "Santiago Yaitepec": "497",
        "San Juan Lachao": "202",
        "Santa María Temaxcaltepec": "433",
        "Santos Reyes Nopala": "526",
        "San Gabriel Mixtepec": "153",
        "San Pedro Mixtepec -Dto. 22 -": "318"
    },
    "Puebla": {
        "Puebla": "114",
        "Tlaltenango": "181",
        "San Miguel Xoxtla": "136",
        "Juan C. Bonilla": "090",
        "Coronango": "034",
        "Cuautlancingo": "041",
        "San Pedro Cholula": "140",
        "San Andrés Cholula": "119",
        "Ocoyucan": "106",
        "Amozoc": "015",
        "Francisco Z. Mena": "064",
        "Pantepec": "111",
        "Venustiano Carranza": "194",
        "Jalpan": "086",
        "Tlaxco": "187",
        "Tlacuilotepec": "178",
        "Xicotepec": "197",
        "Pahuatlán": "109",
        "Honey": "057",
        "Naupan": "100",
        "Huauchinango": "071",
        "Ahuazotepec": "008",
        "Juan Galindo": "091",
        "Tlaola": "183",
        "Zihuateutla": "213",
        "Jopala": "089",
        "Tlapacoya": "184",
        "Chignahuapan": "053",
        "Zacatlán": "208",
        "Chiconcuautla": "049",
        "Ahuacatlán": "006",
        "Tepetzintla": "167",
        "San Felipe Tepatlán": "123",
        "Amixtlán": "014",
        "Tepango de Rodríguez": "162",
        "Zongozotla": "215",
        "Hermenegildo Galeana": "068",
        "Olintla": "107",
        "Coatepec": "030",
        "Camocuautla": "028",
        "Hueytlalpan": "077",
        "Zapotitlán de Méndez": "210",
        "Huitzilan de Serdán": "078",
        "Xochitlán de Vicente Suárez": "202",
        "Huehuetla": "072",
        "Ixtepec": "084",
        "Atlequizayan": "080",
        "Tenampulco": "158",
        "Tuzamapan de Galeana": "192",
        "Caxhuacan": "029",
        "Jonotla": "088",
        "Zoquiapan": "216",
        "Nauzontla": "101",
        "Cuetzalan del Progreso": "043",
        "Ayotoxco de Guerrero": "025",
        "Hueytamalco": "076",
        "Acateno": "002",
        "Cuautempan": "039",
        "Aquixtla": "016",
        "Tetela de Ocampo": "172",
        "Xochiapulco": "200",
        "Zacapoaxtla": "207",
        "Zaragoza": "211",
        "Ixtacamaxtitlán": "083",
        "Zautla": "212",
        "Ocotepec": "105",
        "Libres": "094",
        "Teziutlán": "174",
        "Tlatlauquitepec": "186",
        "Yaonáhuac": "204",
        "Hueyapan": "075",
        "Teteles de Ávila Castillo": "173",
        "Atempan": "017",
        "Chignautla": "054",
        "Xiutetelco": "199",
        "Cuyoaco": "044",
        "Tepeyahualco": "170",
        "San Martín Texmelucan": "132",
        "Tlahuapan": "180",
        "San Matías Tlalancaleca": "134",
        "San Salvador el Verde": "143",
        "San Felipe Teotlalcingo": "122",
        "Chiautzingo": "048",
        "Huejotzingo": "074",
        "Domingo Arenas": "060",
        "Calpan": "026",
        "San Nicolás de los Ranchos": "138",
        "Atlixco": "019",
        "Nealtican": "102",
        "San Jerónimo Tecuanipan": "126",
        "San Gregorio Atzompa": "125",
        "Tochimilco": "188",
        "Tianguismanalco": "175",
        "Santa Isabel Cholula": "148",
        "Huaquechula": "069",
        "San Diego la Mesa Tochimiltzingo": "121",
        "Tepeojuma": "166",
        "Izúcar de Matamoros": "085",
        "Atzitzihuacán": "022",
        "Acteopan": "005",
        "Cohuecan": "033",
        "Tepemaxalco": "165",
        "Tlapanalá": "185",
        "Tepexco": "168",
        "Tilapa": "176",
        "Chietla": "051",
        "Atzala": "021",
        "Teopantlán": "159",
        "San Martín Totoltepec": "133",
        "Xochiltepec": "201",
        "Epatlán": "062",
        "Ahuatlán": "007",
        "Coatzingo": "031",
        "Santa Catarina Tlaltempan": "146",
        "Chigmecatitlán": "052",
        "Zacapala": "206",
        "Tepexi de Rodríguez": "169",
        "Teotlalco": "160",
        "Jolalpan": "087",
        "Huehuetlán el Chico": "073",
        "Chiautla": "047",
        "Cohetzala": "032",
        "Xicotlán": "198",
        "Chila de la Sal": "056",
        "Ixcamilpa de Guerrero": "081",
        "Albino Zertuche": "011",
        "Tulcingo": "191",
        "Tehuitzingo": "157",
        "Cuayuca de Andrade": "042",
        "Santa Inés Ahuatempan": "147",
        "Axutla": "024",
        "Chinantla": "059",
        "Ahuehuetitla": "009",
        "San Pablo Anicano": "139",
        "Tecomatlán": "155",
        "Piaxtla": "113",
        "Guadalupe": "066",
        "Ixcaquixtla": "082",
        "Coyotepec": "037",
        "Xayacatlán de Bravo": "196",
        "Totoltepec de Guerrero": "190",
        "Acatlán": "003",
        "San Jerónimo Xayacatlán": "127",
        "San Pedro Yeloixtlahuaca": "141",
        "Petlalcingo": "112",
        "San Miguel Ixitlán": "135",
        "Chila": "055",
        "Rafael Lara Grajales": "117",
        "San José Chiapa": "128",
        "Oriental": "108",
        "San Nicolás Buenos Aires": "137",
        "Guadalupe Victoria": "067",
        "Tlachichuca": "179",
        "Lafragua": "093",
        "Chilchotla": "058",
        "Quimixtlán": "116",
        "Chichiquila": "050",
        "Tepatlaxco de Hidalgo": "163",
        "Acajete": "001",
        "Nopalucan": "104",
        "Mazapiltepec de Juárez": "096",
        "Soltepec": "152",
        "Acatzingo": "004",
        "San Salvador el Seco": "142",
        "General Felipe Ángeles": "065",
        "Aljojuca": "012",
        "San Juan Atenco": "130",
        "Tepeaca": "164",
        "Cuautinchán": "040",
        "Tecali de Herrera": "153",
        "Mixtla": "097",
        "Santo Tomás Hueyotlipan": "151",
        "Tzicatlacoyan": "193",
        "Huehuetlán el Grande": "150",
        "La Magdalena Tlatlauquitepec": "095",
        "San Juan Atzompa": "131",
        "Huatlatlauca": "070",
        "Los Reyes de Juárez": "118",
        "Cuapiaxtla de Madero": "038",
        "San Salvador Huixcolotla": "144",
        "Quecholac": "115",
        "Tecamachalco": "154",
        "Palmar de Bravo": "110",
        "Chalchicomula de Sesma": "045",
        "Atzitzintla": "023",
        "Esperanza": "063",
        "Cañada Morelos": "099",
        "Tlanepantla": "182",
        "Tochtepec": "189",
        "Atoyatempan": "020",
        "Tepeyahualco de Cuauhtémoc": "171",
        "Huitziltepec": "079",
        "Molcaxac": "098",
        "Xochitlán Todos Santos": "203",
        "Yehualtepec": "205",
        "Tlacotepec de Benito Juárez": "177",
        "Juan N. Méndez": "092",
        "Tehuacán": "156",
        "Tepanco de López": "161",
        "Chapulco": "046",
        "Santiago Miahuatlán": "149",
        "Nicolás Bravo": "103",
        "Atexcal": "018",
        "San Antonio Cañada": "120",
        "Zapotitlán": "209",
        "San Gabriel Chilac": "124",
        "Caltepec": "027",
        "Vicente Guerrero": "195",
        "Ajalpan": "010",
        "Eloxochitlán": "061",
        "Zoquitlán": "217",
        "San Sebastián Tlacotepec": "145",
        "Altepexi": "013",
        "Zinacatepec": "214",
        "San José Miahuatlán": "129",
        "Coxcatlán": "035",
        "Coyomeapan": "036"
    },
    "Queretaro": {
        "Querétaro": "014",
        "El Marqués": "011",
        "Colón": "005",
        "Pinal de Amoles": "002",
        "Jalpan de Serra": "009",
        "Landa de Matamoros": "010",
        "Arroyo Seco": "003",
        "Peñamiller": "013",
        "Cadereyta de Montes": "004",
        "San Joaquín": "015",
        "Tolimán": "018",
        "Ezequiel Montes": "007",
        "Pedro Escobedo": "012",
        "Tequisquiapan": "017",
        "San Juan del Río": "016",
        "Amealco de Bonfil": "001",
        "Corregidora": "006",
        "Huimilpan": "008"
    },
    "Quintana Roo": {
        "Othón P. Blanco": "004",
        "Felipe Carrillo Puerto": "002",
        "Lázaro Cárdenas": "007",
        "Isla Mujeres": "003",
        "Benito Juárez": "005",
        "Puerto Morelos": "011",
        "Cozumel": "001",
        "Solidaridad": "008",
        "Tulum": "009",
        "José María Morelos": "006",
        "Bacalar": "010"
    },
    "San Luis Potosi": {
        "San Luis Potosí": "028",
        "Soledad de Graciano Sánchez": "035",
        "Cerro de San Pedro": "009",
        "Ahualulco": "001",
        "Mexquitic de Carmona": "021",
        "Villa de Arriaga": "046",
        "Vanegas": "044",
        "Cedral": "007",
        "Catorce": "006",
        "Charcas": "015",
        "Salinas": "025",
        "Santo Domingo": "033",
        "Villa de Ramos": "049",
        "Matehuala": "020",
        "Villa de la Paz": "048",
        "Villa de Guadalupe": "047",
        "Guadalcázar": "017",
        "Moctezuma": "022",
        "Venado": "045",
        "Villa de Arista": "056",
        "Villa Hidalgo": "051",
        "Armadillo de los Infante": "004",
        "Ciudad Valles": "013",
        "Ebano": "016",
        "Tamuín": "040",
        "El Naranjo": "058",
        "Ciudad del Maíz": "010",
        "Alaquines": "002",
        "Cárdenas": "005",
        "Cerritos": "008",
        "Villa Juárez": "052",
        "San Nicolás Tolentino": "030",
        "Villa de Reyes": "050",
        "Zaragoza": "055",
        "Santa María del Río": "032",
        "Tierra Nueva": "043",
        "Rioverde": "024",
        "Ciudad Fernández": "011",
        "San Ciro de Acosta": "027",
        "Tamasopo": "036",
        "Rayón": "023",
        "Aquismón": "003",
        "Lagunillas": "019",
        "Santa Catarina": "031",
        "Tancanhuitz": "012",
        "Tanlajás": "041",
        "San Vicente Tancuayalab": "034",
        "San Antonio": "026",
        "Tanquián de Escobedo": "042",
        "Tampamolón Corona": "039",
        "Coxcatlán": "014",
        "Huehuetlán": "018",
        "Xilitla": "054",
        "Axtla de Terrazas": "053",
        "Tampacán": "038",
        "San Martín Chalchicuautla": "029",
        "Tamazunchale": "037",
        "Matlapa": "057"
    },
    "Sinaloa": {
        "Culiacán": "006",
        "Navolato": "018",
        "Badiraguato": "003",
        "Cosalá": "005",
        "Mocorito": "013",
        "Guasave": "011",
        "Ahome": "001",
        "Salvador Alvarado": "015",
        "Angostura": "002",
        "Choix": "007",
        "El Fuerte": "010",
        "Sinaloa": "017",
        "Mazatlán": "012",
        "Escuinapa": "009",
        "Concordia": "004",
        "Elota": "008",
        "Rosario": "014",
        "San Ignacio": "016"
    },
    "Sonora": {
        "Hermosillo": "030",
        "San Miguel de Horcasitas": "056",
        "Carbó": "020",
        "San Luis Río Colorado": "055",
        "Puerto Peñasco": "048",
        "General Plutarco Elías Calles": "070",
        "Caborca": "017",
        "Altar": "004",
        "Tubutama": "065",
        "Atil": "007",
        "Oquitoa": "046",
        "Sáric": "060",
        "Benjamín Hill": "016",
        "Trincheras": "064",
        "Pitiquito": "047",
        "Nogales": "043",
        "Imuris": "035",
        "Santa Cruz": "059",
        "Magdalena": "036",
        "Naco": "039",
        "Agua Prieta": "002",
        "Fronteras": "027",
        "Nacozari de García": "041",
        "Bavispe": "015",
        "Bacerac": "010",
        "Huachinera": "031",
        "Nácori Chico": "040",
        "Granados": "028",
        "Bacadéhuachi": "008",
        "Cumpas": "023",
        "Huásabas": "032",
        "Moctezuma": "038",
        "Villa Hidalgo": "067",
        "Santa Ana": "058",
        "Cananea": "019",
        "Arizpe": "006",
        "Cucurpe": "022",
        "Bacoachi": "011",
        "San Pedro de la Cueva": "057",
        "Divisaderos": "024",
        "Tepache": "063",
        "Villa Pesqueira": "068",
        "Opodepe": "045",
        "Huépac": "034",
        "Banámichi": "013",
        "Ures": "066",
        "Aconchi": "001",
        "Baviácora": "014",
        "San Felipe de Jesús": "053",
        "Rayón": "050",
        "Cajeme": "018",
        "Navojoa": "042",
        "Huatabampo": "033",
        "Bácum": "012",
        "Etchojoa": "026",
        "Benito Juárez": "071",
        "Empalme": "025",
        "Guaymas": "029",
        "San Ignacio Río Muerto": "072",
        "La Colorada": "021",
        "Mazatán": "037",
        "Suaqui Grande": "062",
        "Sahuaripa": "052",
        "San Javier": "054",
        "Soyopa": "061",
        "Bacanora": "009",
        "Arivechi": "005",
        "Rosario": "051",
        "Quiriego": "049",
        "Ónavas": "044",
        "Álamos": "003",
        "Yécora": "069"
    },
    "Tabasco": {
        "Centro": "004",
        "Jalpa de Méndez": "010",
        "Nacajuca": "013",
        "Comalcalco": "005",
        "Huimanguillo": "008",
        "Cárdenas": "002",
        "Paraíso": "014",
        "Cunduacán": "006",
        "Macuspana": "012",
        "Centla": "003",
        "Jonuta": "011",
        "Teapa": "016",
        "Jalapa": "009",
        "Tacotalpa": "015",
        "Tenosique": "017",
        "Balancán": "001",
        "Emiliano Zapata": "007"
    },
    "Tamaulipas": {
        "Victoria": "041",
        "Llera": "019",
        "Güémez": "013",
        "Casas": "008",
        "Matamoros": "022",
        "Valle Hermoso": "040",
        "San Fernando": "035",
        "Cruillas": "010",
        "San Nicolás": "036",
        "Soto la Marina": "037",
        "Jiménez": "018",
        "San Carlos": "034",
        "Abasolo": "001",
        "Padilla": "030",
        "Hidalgo": "016",
        "Mainero": "020",
        "Villagrán": "042",
        "Tula": "039",
        "Jaumave": "017",
        "Miquihuana": "026",
        "Bustamante": "006",
        "Palmillas": "031",
        "Ocampo": "029",
        "Nuevo Laredo": "027",
        "Miguel Alemán": "025",
        "Guerrero": "014",
        "Mier": "024",
        "Gustavo Díaz Ordaz": "015",
        "Camargo": "007",
        "Reynosa": "032",
        "Río Bravo": "033",
        "Méndez": "023",
        "Burgos": "005",
        "Tampico": "038",
        "Ciudad Madero": "009",
        "Altamira": "003",
        "Aldama": "002",
        "González": "012",
        "Xicoténcatl": "043",
        "Gómez Farías": "011",
        "El Mante": "021",
        "Antiguo Morelos": "004",
        "Nuevo Morelos": "028"
    },
    "Tlaxcala": {
        "Tlaxcala": "033",
        "Ixtacuixtla de Mariano Matamoros": "015",
        "Santa Ana Nopalucan": "056",
        "Panotla": "024",
        "Totolac": "036",
        "Tepeyanco": "029",
        "Santa Isabel Xiloxoxtla": "060",
        "San Juan Huactzinco": "053",
        "Calpulalpan": "006",
        "Sanctórum de Lázaro Cárdenas": "020",
        "Benito Juárez": "045",
        "Hueyotlipan": "014",
        "Tlaxco": "034",
        "Nanacamilpa de Mariano Arista": "021",
        "Españita": "012",
        "Apizaco": "005",
        "Atlangatepec": "003",
        "Muñoz de Domingo Arenas": "011",
        "Tetla de la Solidaridad": "031",
        "Xaltocan": "040",
        "San Lucas Tecopilco": "055",
        "Yauhquemehcan": "043",
        "Xaloztoc": "039",
        "Tocatlán": "035",
        "Tzompantepec": "038",
        "San José Teacalco": "052",
        "Huamantla": "013",
        "Terrenate": "030",
        "Lázaro Cárdenas": "047",
        "Emiliano Zapata": "046",
        "Atltzayanca": "004",
        "Cuapiaxtla": "008",
        "El Carmen Tequexquitla": "007",
        "Ixtenco": "016",
        "Ziltlaltépec de Trinidad Sánchez Santos": "037",
        "Apetatitlán de Antonio Carvajal": "002",
        "Amaxac de Guerrero": "001",
        "Santa Cruz Tlaxcala": "026",
        "Cuaxomulco": "009",
        "Contla de Juan Cuamatzi": "018",
        "Tepetitla de Lardizábal": "019",
        "Natívitas": "023",
        "Santa Apolonia Teacalco": "057",
        "Tetlatlahuca": "032",
        "San Damián Texóloc": "049",
        "San Jerónimo Zacualpan": "051",
        "Zacatelco": "044",
        "San Lorenzo Axocomanitla": "054",
        "Santa Catarina Ayometla": "058",
        "Xicohtzinco": "042",
        "Papalotla de Xicohténcatl": "041",
        "Chiautempan": "010",
        "La Magdalena Tlaltelulco": "048",
        "San Francisco Tetlanohcan": "050",
        "Teolocholco": "028",
        "Acuamanala de Miguel Hidalgo": "022",
        "Santa Cruz Quilehtla": "059",
        "Mazatecochco de José María Morelos": "017",
        "Tenancingo": "027",
        "San Pablo del Monte": "025"
    },
    "Veracruz": {
        "Xalapa": "087",
        "Tlalnelhuayocan": "182",
        "Xico": "092",
        "Ixhuacán de los Reyes": "079",
        "Ayahualulco": "025",
        "Perote": "128",
        "Banderilla": "026",
        "Rafael Lucio": "136",
        "Acajete": "001",
        "Las Vigas de Ramírez": "132",
        "Villa Aldama": "194",
        "Tlacolulan": "177",
        "Tonayán": "187",
        "Coacoatzintla": "036",
        "Jilotepec": "093",
        "Naolinco": "112",
        "Miahuatlán": "106",
        "Acatlán": "002",
        "Tepetlán": "166",
        "Juchique de Ferrer": "095",
        "Alto Lucero de Gutiérrez Barrios": "009",
        "Actopan": "004",
        "Coatepec": "038",
        "Teocelo": "164",
        "Cosautlán de Carvajal": "046",
        "Emiliano Zapata": "065",
        "Apazapan": "017",
        "Puente Nacional": "134",
        "Ursulo Galván": "191",
        "Paso de Ovejas": "126",
        "La Antigua": "016",
        "Veracruz": "193",
        "Pánuco": "123",
        "Pueblo Viejo": "133",
        "Tampico Alto": "152",
        "Tempoal": "161",
        "Ozuluama de Mascareñas": "121",
        "Tantoyuca": "155",
        "Platón Sánchez": "129",
        "Chiconamel": "056",
        "Chalma": "055",
        "Chontla": "063",
        "Citlaltépetl": "035",
        "Ixcatepec": "078",
        "Naranjos Amatlán": "013",
        "El Higo": "205",
        "Chinampa de Gorostiza": "060",
        "Tantima": "154",
        "Tamalín": "150",
        "Cerro Azul": "034",
        "Tepetzintla": "167",
        "Tancoco": "153",
        "Tamiahua": "151",
        "Huayacocotla": "072",
        "Ilamatlán": "076",
        "Zontecomatlán de López y Fuentes": "202",
        "Texcatepec": "170",
        "Zacualpan": "198",
        "Benito Juárez": "027",
        "Tlachichilco": "180",
        "Ixhuatlán de Madero": "083",
        "Chicontepec": "058",
        "Álamo Temapache": "160",
        "Tuxpan": "189",
        "Tihuatlán": "175",
        "Castillo de Teayo": "157",
        "Cazones de Herrera": "033",
        "Zozocolco de Hidalgo": "203",
        "Chumatlán": "064",
        "Coxquihui": "050",
        "Mecatlán": "103",
        "Filomeno Mata": "067",
        "Coahuitlán": "037",
        "Coyutla": "051",
        "Coatzintla": "040",
        "Espinal": "066",
        "Poza Rica de Hidalgo": "131",
        "Papantla": "124",
        "Gutiérrez Zamora": "069",
        "Tecolutla": "158",
        "Martínez de la Torre": "102",
        "San Rafael": "211",
        "Tlapacoyan": "183",
        "Jalacingo": "086",
        "Atzalan": "023",
        "Altotonga": "010",
        "Las Minas": "107",
        "Tatatila": "156",
        "Tenochtitlán": "163",
        "Nautla": "114",
        "Misantla": "109",
        "Landero y Coss": "096",
        "Chiconquiaco": "057",
        "Yecuatla": "197",
        "Colipa": "042",
        "Vega de Alatorre": "192",
        "Jalcomulco": "088",
        "Tlaltetela": "024",
        "Tenampa": "162",
        "Totutla": "188",
        "Sochiapa": "146",
        "Tlacotepec de Mejía": "179",
        "Huatusco": "071",
        "Calcahualco": "029",
        "Alpatláhuac": "008",
        "Coscomatepec": "047",
        "La Perla": "127",
        "Chocamán": "062",
        "Tomatlán": "186",
        "Ixhuatlán del Café": "080",
        "Tepatlaxco": "165",
        "Comapa": "043",
        "Zentla": "200",
        "Camarón de Tejeda": "007",
        "Soledad de Doblado": "148",
        "Manlio Fabio Altamirano": "100",
        "Jamapa": "090",
        "Medellín de Bravo": "105",
        "Boca del Río": "028",
        "Orizaba": "118",
        "Rafael Delgado": "135",
        "Mariano Escobedo": "101",
        "Ixhuatlancillo": "081",
        "Atzacan": "022",
        "Ixtaczoquitlán": "085",
        "Fortín": "068",
        "Córdoba": "044",
        "Maltrata": "099",
        "Nogales": "115",
        "Río Blanco": "138",
        "Camerino Z. Mendoza": "030",
        "Aquila": "018",
        "Acultzingo": "006",
        "Soledad Atzompa": "147",
        "Huiloapan de Cuauhtémoc": "074",
        "Tlaquilpa": "184",
        "Astacinga": "019",
        "Xoxocotla": "195",
        "Atlahuilco": "020",
        "Tequila": "168",
        "San Andrés Tenejapan": "140",
        "Tlilapan": "185",
        "Magdalena": "098",
        "Naranjal": "113",
        "Coetzala": "041",
        "Omealca": "117",
        "Cuitláhuac": "053",
        "Cuichapa": "052",
        "Yanga": "196",
        "Amatlán de los Reyes": "014",
        "Atoyac": "021",
        "Paso del Macho": "125",
        "Carrillo Puerto": "031",
        "Cotaxtla": "049",
        "Zongolica": "201",
        "Tehuipango": "159",
        "Mixtla de Altamirano": "110",
        "Los Reyes": "137",
        "Texhuacán": "171",
        "Tezonapa": "173",
        "Tierra Blanca": "174",
        "Tlalixcoyan": "181",
        "Ignacio de la Llave": "075",
        "Alvarado": "011",
        "Lerdo de Tejada": "097",
        "Tres Valles": "207",
        "Carlos A. Carrillo": "208",
        "Cosamaloapan de Carpio": "045",
        "Ixmatlahuacan": "084",
        "Acula": "005",
        "Amatitlán": "012",
        "Tlacotalpan": "178",
        "Saltabarranca": "139",
        "Otatitlán": "119",
        "Tlacojalpan": "176",
        "Tuxtilla": "190",
        "Chacaltianguis": "054",
        "José Azueta": "169",
        "Playa Vicente": "130",
        "Santiago Sochiapan": "212",
        "Isla": "077",
        "Juan Rodríguez Clara": "094",
        "San Andrés Tuxtla": "141",
        "Santiago Tuxtla": "143",
        "Angel R. Cabada": "015",
        "Hueyapan de Ocampo": "073",
        "Catemaco": "032",
        "Soteapan": "149",
        "Mecayapan": "104",
        "Tatahuicapan de Juárez": "209",
        "Pajapan": "122",
        "Chinameca": "059",
        "Acayucan": "003",
        "San Juan Evangelista": "142",
        "Sayula de Alemán": "144",
        "Oluta": "116",
        "Soconusco": "145",
        "Texistepec": "172",
        "Jáltipan": "089",
        "Zaragoza": "199",
        "Oteapan": "120",
        "Cosoleacaque": "048",
        "Nanchital de Lázaro Cárdenas del Río": "206",
        "Ixhuatlán del Sureste": "082",
        "Moloacán": "111",
        "Coatzacoalcos": "039",
        "Agua Dulce": "204",
        "Minatitlán": "108",
        "Hidalgotitlán": "070",
        "Jesús Carranza": "091",
        "Las Choapas": "061",
        "Uxpanapa": "210"
    },
    "Yucatan": {
        "Mérida": "050",
        "Progreso": "059",
        "Chicxulub Pueblo": "020",
        "Ixil": "039",
        "Conkal": "013",
        "Yaxkukul": "105",
        "Hunucmá": "038",
        "Ucú": "100",
        "Kinchil": "044",
        "Tetiz": "087",
        "Celestún": "011",
        "Kanasín": "041",
        "Timucuy": "090",
        "Acanceh": "002",
        "Tixpéhual": "095",
        "Umán": "101",
        "Telchac Pueblo": "082",
        "Dzemul": "026",
        "Telchac Puerto": "083",
        "Cansahcab": "009",
        "Sinanché": "068",
        "Yobaín": "106",
        "Motul": "052",
        "Baca": "004",
        "Mocochá": "051",
        "Muxupip": "054",
        "Cacalchén": "007",
        "Bokobá": "005",
        "Tixkokob": "093",
        "Hoctún": "035",
        "Tahmek": "074",
        "Dzidzantún": "027",
        "Temax": "084",
        "Tekantó": "078",
        "Teya": "088",
        "Suma": "072",
        "Tepakán": "086",
        "Tekal de Venegas": "077",
        "Izamal": "040",
        "Hocabá": "034",
        "Xocchel": "103",
        "Seyé": "067",
        "Cuzamá": "015",
        "Homún": "036",
        "Sanahcat": "064",
        "Huhí": "037",
        "Dzilam González": "029",
        "Dzilam de Bravo": "028",
        "Panabá": "057",
        "San Felipe": "065",
        "Buctzotz": "006",
        "Sucilá": "070",
        "Cenotillo": "012",
        "Dzoncauich": "031",
        "Tunkás": "097",
        "Quintana Roo": "060",
        "Dzitás": "030",
        "Kantunil": "042",
        "Sudzal": "071",
        "Tekit": "080",
        "Sotuta": "069",
        "Tizimín": "096",
        "Río Lagartos": "061",
        "Espita": "032",
        "Temozón": "085",
        "Calotmul": "008",
        "Tinum": "091",
        "Chankom": "017",
        "Chichimilá": "021",
        "Tixcacalcupul": "092",
        "Kaua": "043",
        "Cuncunul": "014",
        "Tekom": "081",
        "Chemax": "019",
        "Valladolid": "102",
        "Uayma": "099",
        "Maxcanú": "048",
        "Samahil": "063",
        "Opichén": "055",
        "Chocholá": "023",
        "Kopomá": "045",
        "Tecoh": "076",
        "Abalá": "001",
        "Halachó": "033",
        "Muna": "053",
        "Sacalum": "062",
        "Maní": "047",
        "Dzan": "025",
        "Chapab": "018",
        "Ticul": "089",
        "Oxkutzcab": "056",
        "Santa Elena": "066",
        "Mama": "046",
        "Chumayel": "024",
        "Mayapán": "049",
        "Teabo": "075",
        "Cantamayec": "010",
        "Yaxcabá": "104",
        "Peto": "058",
        "Chikindzonot": "022",
        "Tahdziú": "073",
        "Tixmehuac": "094",
        "Chacsinkín": "016",
        "Tzucacab": "098",
        "Tekax": "079",
        "Akil": "003"
    },
    "Zacatecas": {
        "Zacatecas": "056",
        "Morelos": "032",
        "Vetagrande": "050",
        "Concepción del Oro": "007",
        "Melchor Ocampo": "027",
        "Mazapil": "026",
        "El Salvador": "041",
        "Juan Aldama": "022",
        "Miguel Auza": "029",
        "General Francisco R. Murguía": "014",
        "Río Grande": "039",
        "Villa de Cos": "051",
        "Cañitas de Felipe Pescador": "006",
        "Calera": "005",
        "Pánuco": "037",
        "General Enrique Estrada": "013",
        "Guadalupe": "017",
        "Trancoso": "057",
        "Genaro Codina": "012",
        "Cuauhtémoc": "008",
        "Ojocaliente": "036",
        "General Pánfilo Natera": "016",
        "Luis Moya": "025",
        "Loreto": "024",
        "Villa González Ortega": "053",
        "Noria de Ángeles": "035",
        "Villa García": "052",
        "Pinos": "038",
        "Villa Hidalgo": "054",
        "Fresnillo": "010",
        "Sombrerete": "042",
        "Sain Alto": "040",
        "Valparaíso": "049",
        "Chalchihuites": "009",
        "Jiménez del Teul": "021",
        "Jerez": "020",
        "Monte Escobedo": "031",
        "Susticacán": "043",
        "Villanueva": "055",
        "Tepetongo": "046",
        "El Plateado de Joaquín Amaro": "015",
        "Jalpa": "019",
        "Tabasco": "044",
        "Huanusco": "018",
        "Tlaltenango de Sánchez Román": "048",
        "Momax": "030",
        "Atolinga": "003",
        "Tepechitlán": "045",
        "Benito Juárez": "004",
        "Teúl de González Ortega": "047",
        "Santa María de la Paz": "058",
        "Trinidad García de la Cadena": "011",
        "Mezquital del Oro": "028",
        "Nochistlán de Mejía": "034",
        "Apulco": "002",
        "Apozol": "001",
        "Juchipila": "023",
        "Moyahua de Estrada": "033"
    }
}

console.log(prueba["Chiapas"]["El Porvenir"]);